#ersion: '3.8'

services:
  backend:
    build:
      context: ./Project/backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./Project/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend